### ISSUE TITLE
Could not install the lang ,

### ISSUE THREAD

**Issue by SAVE-POlNT** [peregrine-lang/Peregrine#110]
**Describe the bug**
i could not even install it 
basically , i installed V in my wsl2

V version is 0.2.4

**Screenshots**
![Capture3](https://user-images.githubusercontent.com/44881216/145685686-010de173-3ef5-413e-8f43-6da2ca6109c7.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10 ,wsl2 ubuntu20,04

It might be a new feature of V lang that is causing it ?

btw : i want to help make this lag good , i think i can use it instead of nim to create some simple exe for the moment.

**Comment by SAVE-POlNT** [comment]
fixed it by just adding mut to split_path at line 46

**Comment by procrastinar** [comment]
Peregrine is being rewritten in C++ at the moment, so I do not recommend using the current compiler version of the language.
You can see the development in the [rewrite](https://github.com/peregrine-lang/Peregrine/tree/rewrite) branch.

**Comment by SaptakBhoumik** [comment]
As told by @procrastinar , clone the rewrite branch
Follow the following steps to compile:-

**1)Clone the rewrite branch of https://github.com/peregrine-lang/Peregrine.git**
```bash
git clone -b rewrite https://github.com/peregrine-lang/Peregrine.git
```
**2)Cd into the directory**
```bash 
cd Peregrine
```
**3)Build it**
```bash
meson builddir
cd builddir
ninja
```
This will create the binary of the compiler named ``./peregrine.elf`` in the builddir folder

#Using it
**C++ backend**
To compile it using the c++ backing just run ``./peregrine.elf compile path_to_file.pe`` .It will create the executable named ``./a.out``. Run it to see the result. Check the [can_comp.pe](https://github.com/peregrine-lang/Peregrine/blob/rewrite/can_comp.pe) file in the root directory to know what you can do with the c++ backend at this point 
**JS Backend**
To use the javascript backend use the following command
``./peregrine.elf compile path_to_file.js.pe -js``.
It will create the javascript file named ``index.js``. Run the generated javascript using ``node index.js``. Check the [can_comp.js.pe](https://github.com/peregrine-lang/Peregrine/blob/rewrite/can_comp.js.pe) file in the root directory to know what you can do with the js backend at this point

**Comment by SaptakBhoumik** [comment]
Use the main branch because we have merged rewrite with main.
I am closing it due to  inactivity
