### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by YashVardhan-AI** [peregrine-lang/Peregrine#117]
Is there any documentation one can refer to in order to learn to use this language.
Oh and can we use external libs right now??

**Comment by SaptakBhoumik** [comment]
Unfortunately, there is no proper docs at this moment. You can refer to https://github.com/peregrine-lang/Peregrine/blob/main/can_comp.pe to learn about its syntax.

>  Oh and can we use external libs right now??

Soon

**Comment by YashVardhan-AI** [comment]
ah ok
