### ISSUE TITLE
There are too many errors when compile the .pe file from the peregrine.elf compiler

### ISSUE THREAD

**Issue by PhamXD** [peregrine-lang/Peregrine#126]
**Describe the bug**
It seems that the above error does not arise from the compiler but due to the syntax of the C++ language (occurring in temp.cc)
The versions have been installed: `meson 0.62.2` `ninja 1.10.2.git.kitware.jobserver-1` `clang 14.0.3`

**To Reproduce**
1. Go to 'Peregrine' folder
2. Run commands 'meson builddir' -> 'cd builddir' -> 'ninja'
3. Compile './peregrine compile ../can_comp.pe'

**Expected behavior**
compile can_comp.pe successfully

**Screenshots**
![bug](https://user-images.githubusercontent.com/105527161/172033479-be148f2a-c2c4-4b9c-8dba-41d11d9e4f97.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 10.0.19043.1706 (for windows)

**Comment by SaptakBhoumik** [comment]
@PhamXD I have fixed this issue. Let me know if it works or not

**Comment by PhamXD** [comment]
Thank @SaptakBhoumik, the issue #126 has been fixed and it worked as my expected!

**Comment by PhamXD** [comment]
Thank @SaptakBhoumik, the issue #126 has been fixed and it worked as my expected!
