### ISSUE TITLE
Peregrine logo

### ISSUE THREAD

**Issue by oz123** [peregrine-lang/Peregrine#129]
:hand: this looks like a really cool project. I'll definitely follow this.
One tiny thing that immediately stands out is the project's logo. It looks more like a barn swallow than a peregrine.
Both are fast birds, and swallow is really a bad name for a programming language.
You can ignore this cosmetic issue, or ... I can offer create a new logo based on the shadow of a diving peregrine.

**Comment by SaptakBhoumik** [comment]
You can if you want but just try to follow the format as present in the graphics folder and follow the black and white colour scheme
