### ISSUE TITLE
Isn't this more of a transpiler than a programming language?

### ISSUE THREAD

**Issue by frankhart2018** [peregrine-lang/Peregrine#13]
I saw that your code generates C instead of assembly. Doesn't this make it a transpiler, rather than a compiler? Also, it will be as fast as C when you generate C :).

**Comment by SaptakBhoumik** [comment]
Well no, it is not a python to c transcompiler. If you consider it a transcompiler then languages like V and nim are also transcompiler

**Comment by somebody1234** [comment]
if you generate assembly, isn't it a transpiler to assembly...

**Comment by somebody1234** [comment]
also this is like saying an interpreter would not even remotely be related to programming languages

**Comment by SaptakBhoumik** [comment]
I agree

**Comment by ethanolchik** [comment]
I'll close this issue, since it seems resolved. If you have any more questions, you can create a new discussion.
