### ISSUE TITLE
temp.cc:2:10: fatal error: 'cstdlib' file not found

### ISSUE THREAD

**Issue by pikhovkin** [peregrine-lang/Peregrine#138]
**Describe the bug**
```
temp.cc:2:10: fatal error: 'cstdlib' file not found
#include <cstdlib>
         ^~~~~~~~~
1 error generated.
```

**To Reproduce**
1. git clone https://github.com/peregrine-lang/Peregrine.git
2. Go to 'Peregrine' folder
3. Run commands 'meson builddir' -> 'cd builddir' -> 'ninja'
4. Compile './peregrine.elf compile ../can_comp.pe'
5. See error above

**Desktop (please complete the following information):**
 - OS: Linux Mint 21

**Comment by SaptakBhoumik** [comment]
It is because clang is unable to find cstdlib for some reason. This header file is usually installed by default but still make sure it exists. If it does exist then use the following command (make sure u have g++ for this) 
```
./peregrine.elf -cc g++ compile ../can_comp.pe 
```

**Comment by pikhovkin** [comment]
it works! @SaptakBhoumik thank you!
