### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by Steammake3** [peregrine-lang/Peregrine#140]
I went to [The Peregrine Docs](https://peregrine-lang.github.io), and could find no information on syntax.

**Comment by SaptakBhoumik** [comment]
There's no docs as it is an unfinished project. U can see the can_comp.pe to know about the syntax. Development is currently paused till mid 2024 because I (main dev) am busy with work so you won't get a proper doc before that

**Comment by iperov** [comment]
it looks like yet another dead lang
