### ISSUE TITLE
Comparison docs

### ISSUE THREAD

**Issue by AcousticCh** [peregrine-lang/Peregrine#22]
**Is your feature request related to a problem? Please describe.**

No problems

**Describe the solution you'd like**

I would like to work towards learning swallow as primary language and assist in writing docs and implementing self hosting of the language and stay a consistent contributor to this amazing project I did read contribution.md and didn't see anything about my question which is why I ask here

**Describe alternatives you've considered**

Whether I can or cannot help with the documentation maybe the documentation might have this but I'd be happy make a domain or go under a docs sub domain and write comparisons of swallow and python with examples and explanations

**Additional context**

If I could work towards these goals I would love to become a consistent contributor for swallow as I had my own similar ideas but my experience programming is nowhere near capable and I can see this being what I was looking for and taking a lead in tech a few years from now

**Comment by ethanolchik** [comment]
Hey there! Thanks for taking interest in Peregrine! We'd love your contribution towards Peregrine, The language is currently at a very early stage and 0.0.1 hasn't released yet. I'm not sure when It'd be a good time to start writing docs, @SaptakBhoumik would probably know. Let's wait for him to answer :)

**Comment by AcousticCh** [comment]
Of course! I did take consideration upon how early it is in development. The excitement of wanting to join the cause has me full of questions and ideas is all

**Comment by ethanolchik** [comment]
Haha, cool. You can ask any questions you'd like, I can try my best to answer. Not guaranteed to answer all of them because Saptak knows the language better than anyone

**Comment by SaptakBhoumik** [comment]
@AcousticCh are you asking about a benchmark or a comparison between various languages?

**Comment by AcousticCh** [comment]
I was thinking comparison amongst python and swallow as it's intended to be similar or have ease of learning curve if switching from python to swallow, maybe some benchmark style test could be in that documentation as well and if this idea was implemented and you wanted various other languages in that comparison I would love to work on that, I thought this would be a good way to show the languages capabilities and teach myself the language at the same time

**Comment by AcousticCh** [comment]
Oh and that brings me to ask when I found this repo through the online Article introducing the language and read the README here I thought swallow as the languages name is it officially going to go by swallow or peregrine?

**Comment by SaptakBhoumik** [comment]
> Oh and that brings me to ask when I found this repo through the online Article introducing the language and read the README here I thought swallow as the languages name is it officially going to go by swallow or peregrine?

Well some people were complaining that swallow has a bad meaning so we had to change it. It will be named peregrine

**Comment by AcousticCh** [comment]
Ah I guess I can see their side but I saw your idea of the bird swallow (or at least that's how I understood it)  as opposed to python fitting well, it was definitely a cool way to put it if people could keep their mind out of the gutter

**Comment by SaptakBhoumik** [comment]
I am closing it. If you have more questions please reopen it
