### ISSUE TITLE
Why do I get exit codes different than zero?

### ISSUE THREAD

**Issue by gabriel-milan** [peregrine-lang/Peregrine#40]
**Describe the bug**
I'm developing automated tests for the language, but I'm getting exit codes that differ from zero, even when the script runs fine.

**To Reproduce**
1. Compile peregrine
2. Compile the test script `ccode.pe`
3. Execute the compiled file
4. Exit code is 8

**Expected behavior**
The exit code is supposed to be zero when a script runs fine

**Screenshots**
![image](https://user-images.githubusercontent.com/35741485/136382797-d1e90072-668d-4e39-8453-5adda9080112.png)

**Desktop:**
 - OS: Debian Linux 11
   - Output of `uname -a`: `Linux Vostro-5481 5.10.0-8-amd64 #1 SMP Debian 5.10.46-5 (2021-09-23) x86_64 GNU/Linux`

**Comment by SaptakBhoumik** [comment]
@gabriel-milan Because you have to explicitly mention what exit code you want. 
 ```
def main():
    print("Calling c function\n")
    Ccode printf("It works"); Ccode

```
You are trying to run this and there is no mention of exit code

```
def main()->int:
    print("Calling c function\n")
    Ccode printf("It works"); Ccode
    return 0
```
Use it to get exit status 0
