### ISSUE TITLE
Error when compiling peregrine on Windows

### ISSUE THREAD

**Issue by Ivo-Balbaert** [peregrine-lang/Peregrine#70]
**Describe the bug**

When compiling the Peregrine source with the v compiler:

      v peregrine.v

I get the following error:

c:\Peregrine\Peregrine>v peregrine.v
**builder error: 'libtcc.h' not found**

**To Reproduce**

1. Install v and peregrine exactly as described
2.  v peregrine.v
3. See error

**Expected behavior**
Successfull compilation of peregrine

**Desktop (please complete the following information):**
 - OS: Windows 10/11
 - V 0.2.4 43931be

**Additional info**
The file libtcc.h lives in C:\v\thirdparty\tcc\libtcc

**Comment by SaptakBhoumik** [comment]
@Ivo-Balbaert Follow this tutorial to install libtcc https://www.developing-stuff.com/how-to-compile-run-c-code-at-runtime-or-how-to-use-c-as-a-scripting-language/

C:\v\thirdparty\tcc\libtcc will not work

**Comment by SaptakBhoumik** [comment]
@Ivo-Balbaert please clone the repo again
