### ISSUE TITLE
Error when compiling Peregrine on Linux

### ISSUE THREAD

**Issue by procrastinar** [peregrine-lang/Peregrine#71]
**Describe the bug**
When compiling Peregrine source on Linux with V compiler, I get the following error:
```js
builder error: 'libtcc.h' not found
```

**Desktop (please complete the following information):**
 - OS: Debian Linux

**Comment by SaptakBhoumik** [comment]
@procrastinar You must have libtcc installed

**Comment by ClientCrash** [comment]
Use the `build-linux-full.sh` script

**Comment by procrastinar** [comment]
I installed `libtcc`, but a new error appears: `include file 'stddef.h' not found`.

**Comment by SaptakBhoumik** [comment]
@procrastinar We are rewriting the entire thing because the current thing is not stable. Please give us some time
